// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBToN6M9t6a_0zJ58lmPo8bUbBqLMDGETk',
    appId: '1:686754712481:web:232c24e8399ae1682459e0',
    messagingSenderId: '686754712481',
    projectId: 'sc2024-96b48',
    authDomain: 'sc2024-96b48.firebaseapp.com',
    databaseURL: 'https://sc2024-96b48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sc2024-96b48.appspot.com',
    measurementId: 'G-TZM3DY13K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP8A9ut7Q7ZtfkMbKGSNpj6fC07Plu63M',
    appId: '1:686754712481:android:53ff9bd3df9f9d622459e0',
    messagingSenderId: '686754712481',
    projectId: 'sc2024-96b48',
    databaseURL: 'https://sc2024-96b48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sc2024-96b48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBABMSx8zj0W5evvNO45BDDZb2aF0d7scI',
    appId: '1:686754712481:ios:1daf5773783c5c272459e0',
    messagingSenderId: '686754712481',
    projectId: 'sc2024-96b48',
    databaseURL: 'https://sc2024-96b48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sc2024-96b48.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBABMSx8zj0W5evvNO45BDDZb2aF0d7scI',
    appId: '1:686754712481:ios:9b01b5553a4d55272459e0',
    messagingSenderId: '686754712481',
    projectId: 'sc2024-96b48',
    databaseURL: 'https://sc2024-96b48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sc2024-96b48.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
